name: package-updater
on: 
  push:
    branches:
      - test
jobs:
  update-package:
    runs-on: ubuntu-latest
    steps:
      - run: git subtree push --prefix Assets/VRKeyboard-package origin upm
