name: package-updater
on: 
  push:
    branches:
      - master
jobs:
  update-package:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2.1.0
      - run: | 
          git subtree split --prefix Assets/VRKeyboard-package -b upm
          git push -f origin upm:upm
          git branch -D upm
