name: package-updater
on: 
  push:
    branches:
      - master
jobs:
  update-package:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2.1.0
      - run: git subtree push --prefix Assets/VRKeyboard-package origin upm --force
